var action_markups=require("reflux").createActions([
		"loadTagsets",
		"setActiveTagset",
		"setSelection",
		"tokenPositionUpdated",
		"createMarkup",
		"editMarkup",
		"editMarkupAtPos",
		"saveMarkup",
		"deleteMarkup",
		"cancelEdit",
		"markupUpdated",
		"setVisibleTags",
		"clearAllMarkups",
		"saveMarkups",
		"registerViewid",
		"setVirtualMarkup",
		"addHiddenView",
		"removeHiddenView",
		"doTag",
		"clearMarkupInSelection"
]);
module.exports=action_markups;